language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - pytest tests --cov=api --cov-report term-missing
    - coverage report

after_success:
    - coveralls

