language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - python3 -m pytest --cov=app tests/
    - coverage report

after_success:
    - coveralls